services:
  #Prod API
  - type: web
    name: prod bill-file-analyzer-service
    env: docker
    repo: https://github.com/rgarbi/bill-file-analyzer-service
    branch: main
    region: oregon
    plan: starter
    numInstances: 1
    healthCheckPath: /health_check
    envVars:
      - key: APP__DATABASE__USERNAME
        fromDatabase:
          name: prod bill-file-analyzer-service-db
          property: user
      - key: APP__DATABASE__PASSWORD
        fromDatabase:
          name: prod bill-file-analyzer-service-db
          property: password
      - key: APP__DATABASE__HOST
        fromDatabase:
          name: prod bill-file-analyzer-service-db
          property: host
      - key: APP__DATABASE__PORT
        fromDatabase:
          name: prod bill-file-analyzer-service-db
          property: port
      - key: APP__DATABASE__DATABASE_NAME
        fromDatabase:
          name: prod bill-file-analyzer-service-db
          property: database
      - key: APP__APPLICATION__WEB_APP_HOST
        value: https://SOME_APP_WEB_HOST.COM
      - key: APP__AUTH_CONFIG__AUDIENCE
        value: https://SOME_AUTH_CONFIG_AUDIENCE.COM
      - key: APP__AUTH_CONFIG__ISSUER
        value: https://SOME_AUTH_CONFIG_ISSUER
      - key: APP__AUTH_CONFIG__SIGNING_KEY
        generateValue: true
      - key: APP__EMAIL_CLIENT__API_KEY
        sync: false
      - key: APP__EMAIL_CLIENT__BASE_URL
        value: https://api.sendgrid.com
      - key: APP__EMAIL_CLIENT__SENDER_EMAIL
        value: EMAIL_CLIENT_SENDER_EMAil

  #STAGING API
  - type: web
    name: staging bill-file-analyzer-service
    env: docker
    repo: https://github.com/rgarbi/bill-file-analyzer-service
    branch: staging
    region: oregon
    plan: starter
    numInstances: 1
    healthCheckPath: /health_check
    envVars:
      - key: APP__DATABASE__USERNAME
        fromDatabase:
          name: staging bill-file-analyzer-service-db
          property: user
      - key: APP__DATABASE__PASSWORD
        fromDatabase:
          name: staging bill-file-analyzer-service-db
          property: password
      - key: APP__DATABASE__HOST
        fromDatabase:
          name: staging bill-file-analyzer-service-db
          property: host
      - key: APP__DATABASE__PORT
        fromDatabase:
          name: staging bill-file-analyzer-service-db
          property: port
      - key: APP__DATABASE__DATABASE_NAME
        fromDatabase:
          name: staging bill-file-analyzer-service-db
          property: database
      - key: APP__APPLICATION__WEB_APP_HOST
        value: https://SOME_APP_WEB_HOST.COM
      - key: APP__AUTH_CONFIG__AUDIENCE
        value: https://SOME_AUTH_CONFIG_AUDIENCE.COM
      - key: APP__AUTH_CONFIG__ISSUER
        value: https://SOME_AUTH_CONFIG_ISSUER
      - key: APP__AUTH_CONFIG__SIGNING_KEY
        generateValue: true
      - key: APP__EMAIL_CLIENT__API_KEY
        sync: false
      - key: APP__EMAIL_CLIENT__BASE_URL
        value: https://api.sendgrid.com
      - key: APP__EMAIL_CLIENT__SENDER_EMAIL
        value: EMAIL_CLIENT_SENDER_EMAil

databases:
  - name: prod bill-file-analyzer-service-db
    plan: starter
    region: oregon
    databaseName: prod_bill-file-analyzer-service_db
  - name: staging bill-file-analyzer-service-db
    plan: starter
    region: oregon
    databaseName: staging_bill-file-analyzer-service_db
